### ISSUE TITLE
Issues installing third-party libraries for GCHP with CMake

### ISSUE THREAD

**Issue by lizziel** [LiamBindle/gchp#7]
I am following the Compiling GCHP with CMake tutorial at wiki/Compiling-GCHP-with-CMake. I run into problems in Step 2 ("Run CMake to configure the build and generate the build scripts").

I first ran into an issue at the "cmake .." step, getting the message that my cmake version was too old. The error handling for this was clear and I following the instructions to update to 3.0.2 or higher.

 /local/elundgren/gchp-thirdparty $ cmake --version
cmake version 2.8.12.2
 /local/elundgren/gchp-thirdparty $ module load cmake/3.12.1-fasrc01

I then tried again but got an error that my install location was not writable. 

 /local/elundgren/gchp-thirdparty $ cd build
 /local/elundgren/gchp-thirdparty/build $ ls
CMakeCache.txt  CMakeFiles/
 /local/elundgren/gchp-thirdparty/build $ cmake ..
-- The Fortran compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (message):
  Invalid install location.  You don't have write permissions for
  "/usr/local".

  Set CMAKE_INSTALL_PREFIX to a location where files can be installed.

-- Configuring incomplete, errors occurred!
See also "/local/elundgren/gchp-thirdparty/build/CMakeFiles/CMakeOutput.log".

To fix this I created an install folder and added this text to gchp-thirdparty/CMakeLists.txt:
set(CMAKE_INSTALL_PREFIX /local/elundgren/install)

Trying again, I got the following message:

 /local/elundgren/gchp-thirdparty/build $ cmake ..
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
-- Could NOT find MPI_Fortran (missing: MPI_Fortran_LIB_NAMES MPI_Fortran_F77_HEADER_DIR MPI_Fortran_MODULE_DIR MPI_Fortran_WORKS) 
CMake Error at /n/sw/helmod/apps/centos7/Core/cmake/3.12.1-fasrc01/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND MPI_Fortran_FOUND C
  CXX Fortran)
Call Stack (most recent call first):
  /n/sw/helmod/apps/centos7/Core/cmake/3.12.1-fasrc01/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /n/sw/helmod/apps/centos7/Core/cmake/3.12.1-fasrc01/share/cmake-3.12/Modules/FindMPI.cmake:1666 (find_package_handle_standard_args)
  CMakeLists.txt:18 (find_package)

-- Configuring incomplete, errors occurred!
See also "/local/elundgren/gchp-thirdparty/build/CMakeFiles/CMakeOutput.log".

It seems I need to load modules on my cluster so I sourced my usual environment file that I use for compiling GCHP.

 /local/elundgren/gchp-thirdparty/build $ source ~/init/gchp.ifort17_openmpi_odyssey.env 
Loading modules for GCHP on Odyssey, please wait ...
Modules loaded:

Currently Loaded Modules:
  1) git/2.17.0-fasrc01     3) openmpi/3.1.1-fasrc01   5) szip/2.1-fasrc03      7) netcdf/4.1.3-fasrc03
  2) intel/17.0.4-fasrc01   4) zlib/1.2.8-fasrc08      6) hdf5/1.8.12-fasrc13

/local/elundgren/gchp-thirdparty/build $ module load cmake/3.12.1-fasrc01

I then tried again to do "cmake .." and still got an error:

 /local/elundgren/gchp-thirdparty/build $ cmake ..
CMake Warning (dev) at CMakeLists.txt:18 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable MPI_ROOT is set to:

    /n/helmod/apps/centos7/Comp/intel/17.0.4-fasrc01/openmpi/3.1.1-fasrc01

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found MPI_C: /n/sw/helmod/apps/centos7/Comp/intel/17.0.4-fasrc01/openmpi/3.1.1-fasrc01/lib64/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /n/sw/helmod/apps/centos7/Comp/intel/17.0.4-fasrc01/openmpi/3.1.1-fasrc01/lib64/libmpi_cxx.so (found version "3.1") 
-- Could NOT find MPI_Fortran (missing: MPI_Fortran_WORKS) 
CMake Error at /n/sw/helmod/apps/centos7/Core/cmake/3.12.1-fasrc01/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_Fortran_FOUND Fortran) (found version
  "3.1")
Call Stack (most recent call first):
  /n/sw/helmod/apps/centos7/Core/cmake/3.12.1-fasrc01/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /n/sw/helmod/apps/centos7/Core/cmake/3.12.1-fasrc01/share/cmake-3.12/Modules/FindMPI.cmake:1666 (find_package_handle_standard_args)
  CMakeLists.txt:18 (find_package)

-- Configuring incomplete, errors occurred!
See also "/local/elundgren/gchp-thirdparty/build/CMakeFiles/CMakeOutput.log".

It seems that some environment variables CMake depends on are not set on my cluster. Is this what you think the issue is as well? Do you have a fix for this other than working with cluster sys admins?

**Comment by LiamBindle** [comment]
Hi Lizzie,

Sorry you ran into these problems. I'm in the process of making everything more robust, so this is helpful. I've included a full explanation of what I think is going on, but feel free to skip to the bottom.

---

> I first ran into an issue at the "cmake .." step, getting the message that my cmake version was too old. The error handling for this was clear and I following the instructions to update to 3.0.2 or higher.

The minimum version is actually 3.5, so I'll update this.

> I then tried again but got an error that my install location was not writable.

This is expected. I kind of wish CMake didn't call these "errors", but CMake is just saying it doesn't have write permissions to where it's configured to install to. This "error" is specific to that gchp-thirdparty repo of mine.

> To fix this I created an install folder and added this text to gchp-thirdparty/CMakeLists.txt:
> set(CMAKE_INSTALL_PREFIX /local/elundgren/install)

Actually, rather than modifying the CMakeLists.txt , use the `-D<var name>=<value>` option to set `CMAKE_INSTALL_PREFIX` to `/local/elundgren/install`. So in your case you'd do

```
cmake -DCMAKE_INSTALL_PREFIX=/local/elundgren/install .
```

> It seems I need to load modules on my cluster so I sourced my usual environment file that I use for compiling GCHP.

Yeah, you'll have to load your intel module so that CMake can find your compiler, MPI libraries, etc. You don't actually have to set any environment variables, but they won't hurt. 

> ```
> CMake Warning (dev) at CMakeLists.txt:18 (find_package):
> Policy CMP0074 is not set: find_package uses _ROOT variables.
> Run "cmake --help-policy CMP0074" for policy details. Use the cmake_policy
> command to set the policy and suppress this warning.
> ```

CMake uses "policies" to introduce new behavior, while maintain backwards compatibility. I look this one up in the documentation, and it enables the behavior where CMake will look at environment variables like `MPI_ROOT` if they exist in your environment. This seems like useful behavior so I'll add it (so you won't see that warning in the future). 

------

Now, on to your actual problem:

> ```
> -- Found MPI_C: /n/sw/helmod/apps/centos7/Comp/intel/17.0.4-fasrc01/openmpi/3.1.1-fasrc01/lib64/libmpi.so (found version "3.1")
> -- Found MPI_CXX: /n/sw/helmod/apps/centos7/Comp/intel/17.0.4-fasrc01/openmpi/3.1.1-fasrc01/lib64/libmpi_cxx.so (found version "3.1")
> -- Could NOT find MPI_Fortran (missing: MPI_Fortran_WORKS)
> CMake Error at /n/sw/helmod/apps/centos7/Core/cmake/3.12.1-fasrc01/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
> Could NOT find MPI (missing: MPI_Fortran_FOUND Fortran) (found version "3.1")
> ```

CMake finds C and C++ MPI libraries, but doesn't find MPI's Fortran libraries. 

It appears that when you first ran `cmake`, it chose to GNU compilers since the `CC`, `CXX`, and `FC`  variables weren't set, and they were probably the only compilers before you activated your Intel environment. You can see this from in your first snippet.

> ```
> /local/elundgren/gchp-thirdparty/build $ cmake ..
> -- The Fortran compiler identification is GNU 4.8.5
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working Fortran compiler: /usr/bin/f95
> -- Check for working Fortran compiler: /usr/bin/f95 -- works
> ```

Later, after you activated your Intel environment, the build is still configured for GNU compilers but it's now searching for MPI libraries in your Intel environment.

--- 
## Solution

To fix this, delete your build directory and start over so that CMake configures the build for your intel compilers. Load your intel module and set `CC`, `CXX`, and `FC`  before calling CMake for the first time.  

```sh
# Load your intel module
export CC=icc  # these 3 environment varibles are the only environment variables CMake really cares about
export CXX=icpc
export FC=ifort
cd <path to gchp-thirdparty>
rm -rf build   # delete your build directory to start clean
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/local/elundgren/install ..
```

If that works, then you can `make install`. Let me know if this doesn't work though.



Sorry again for the problem. I'll expand on the instructions to include details about selecting compilers and working in environments.

**Comment by lizziel** [comment]
Thanks Liam. This fixed the issue calling cmake. I now run into an issue in the next step calling make:

 /local/elundgren/gchp-thirdparty/build $ make
.....lots of output....
tree_lib in: /local/elundgren/gchp-thirdparty/ESMF/src/Infrastructure/VM/src
/bin/sh: line 0: [: -ge: unary operator expected
/bin/sh: line 0: [: -ge: unary operator expected
/bin/sh: line 0: [: -ge: unary operator expected
In file included from /local/elundgren/gchp-thirdparty/ESMF/src/Infrastructure/VM/src/ESMCI_VMKernel.C:13:0:
/local/elundgren/gchp-thirdparty/ESMF/src/Infrastructure/VM/src/../include/ESMCI_VMKernel.h:331:2error: #error - Compiler flags do not support OpenMP.
 #error - Compiler flags do not support OpenMP.
  ^
In file included from /local/elundgren/gchp-thirdparty/ESMF/src/Infrastructure/VM/src/../include/ESMCI_VM.h:41:0,
                 from /local/elundgren/gchp-thirdparty/ESMF/src/Infrastructure/VM/src/ESMCI_VM.C:39:
/local/elundgren/gchp-thirdparty/ESMF/src/Infrastructure/VM/src/../include/ESMCI_VMKernel.h:331:2error: #error - Compiler flags do not support OpenMP.
 #error - Compiler flags do not support OpenMP.
  ^
make[11]: *** [/local/elundgren/gchp-thirdparty/ESMF/obj/objO/Linux.intel.64.openmpi.default/ESMCI_VM.o] Error 1
make[11]: *** Waiting for unfinished jobs....
make[11]: *** [/local/elundgren/gchp-thirdparty/ESMF/obj/objO/Linux.intel.64.openmpi.default/ESMCI_VMKernel.o] Error 1
make[10]: *** [esmflib] Error 2
make[9]: *** [tree_lib] Error 2
make[8]: *** [tree] Error 1
make[7]: *** [tree] Error 1
make[6]: *** [tree] Error 1
make[5]: *** [tree] Error 1
make[4]: *** [build_libs] Error 2
make[3]: *** [lib] Error 2
make[2]: *** [ESMF_build-prefix/src/ESMF_build-stamp/ESMF_build-build] Error 2
make[1]: *** [CMakeFiles/ESMF_build.dir/all] Error 2
make: *** [all] Error 2

**Comment by LiamBindle** [comment]
This lends further support to removing ESMF from our build process entirely. What's going wrong is how I'm calling the ESMF Makefiles from the CMakeLists.txt in gchp-thirdparty (usually not recommended...doing it is tricky). 

Rather than us trying to sort this error out, I think it would be best if I just abandon gchp-thirdparty. It (gchp-thirdparty) doesn't really have much to do with the new GCHP build system, so rather than try to fix it, I think I'll just make the proper changes to the new GCHP build system so that ESMF can be used when it's installed independently.

Sorry about that.  I'll let you know when I think it is ready to try again. I probably won't have the chance to get to it before the long weekend, so it will probably be mid to late next week.

Thanks for your time today in giving this a go.
